### ISSUE TITLE
Missing openalpr.framework while executing "bundle exec ./bin/build_frameworks.rb".

### ISSUE THREAD

**Issue by EMakadiya** [twelve17/openalpr-ios#13]
cant't find openalpr.framework while executing "bundle exec ./bin/build_frameworks.rb".
please help me how to get this framework?

**Comment by twelve17** [comment]
Is it in the output directory? If not, can you provide the build.log?

**Comment by EMakadiya** [comment]
I run "bundle exec ./bin/build_frameworks.rb" command and got (leptonica, opencv, tesseract) frameworks but not able to get openalpr.framework.

I am using xcode 7.1.

I m attaching bulid.log file please help me out.

[build.log.zip](https://github.com/twelve17/openalpr-ios/files/54918/build.log.zip)

**Comment by DaidoujiChen** [comment]
Here got the same issue
OSX 10.10.5
ruby 2.1.2p95
Xcode 7.1.1

**Comment by twelve17** [comment]
@EMakadiya @DaidoujiChen can you see if you have autoconf installed? I thought it was included with the Xcode CLI tools, but it seems it was removed long ago.

**Comment by DaidoujiChen** [comment]
Try on tomorrow :)

**Comment by DaidoujiChen** [comment]
Hello @twelve17,

I have autoconf.
`````
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
`````
![2015-12-09 10 07 01](https://cloud.githubusercontent.com/assets/670441/11674523/b7b94878-9e5c-11e5-8f73-ebb16fc9ff87.png)

**Comment by twelve17** [comment]
Hi @DaidoujiChen, 

Thanks for the reply.  I'm at a loss at what it could be.  Can you try to manually go to your `/Volumes/DATA/Project_Stuff/openalpr-ios/work` (or wherever it is in your machine--I'm using @EMakadiya 's examples) and do the automake command command by hand?  e.g.

    ```
     SDKROOT='/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk' \

     CXX='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++' \
     CC='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc' \
     LD='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld' \
     AS='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/as' \
     AR='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar' \
     NM='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm' \
     RANLIB='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib' \
     LDFLAGS='-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/lib/ -L/Volumes/DATA/Project_Stuff/openalpr-ios/work/leptonica-thin-lib/iPhoneOS-armv7' \
     CFLAGS='-arch armv7 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -miphoneos-version-min=9.0 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/include/ -I/Volumes/DATA/Project_Stuff/openalpr-ios/output/leptonica.framework/Headers' \
     CPPFLAGS='-arch armv7 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -miphoneos-version-min=9.0 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/include/ -I/Volumes/DATA/Project_Stuff/openalpr-ios/output/leptonica.framework/Headers' \
     CXXFLAGS='-arch armv7 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -miphoneos-version-min=9.0 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/include/ -I/Volumes/DATA/Project_Stuff/openalpr-ios/output/leptonica.framework/Headers' \
     PATH='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Users/c104/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bin:/Users/c104/.rbenv/versions/2.1.2/bin:/usr/local/Cellar/rbenv/0.4.0/libexec:/Users/c104/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' \
     BUILD_HOST_NAME='arm-apple-darwin7' \
     LIBLEPT_HEADERSDIR='/Volumes/DATA/Project_Stuff/openalpr-ios/output/leptonica.framework/Headers' bash autogen.sh
```

**Comment by DaidoujiChen** [comment]
Hello @twelve17,

Sorry, it's my mistake...
`````
/Users/chilun_chen/Desktop/SourceCode/openalpr-ios-master/lib/alpr/utils.rb:44:in `execute': Child returned: pid 15806 exit 127 (RuntimeError)
	from /Users/chilun_chen/Desktop/SourceCode/openalpr-ios-master/lib/alpr/utils.rb:74:in `log_execute'
	from /Users/chilun_chen/Desktop/SourceCode/openalpr-ios-master/lib/alpr/package/alpr.rb:112:in `build_arch'
	from /Users/chilun_chen/Desktop/SourceCode/openalpr-ios-master/lib/alpr/package/base.rb:53:in `block in install'
	from /Users/chilun_chen/Desktop/SourceCode/openalpr-ios-master/lib/alpr/package/base.rb:52:in `each'
	from /Users/chilun_chen/Desktop/SourceCode/openalpr-ios-master/lib/alpr/package/base.rb:52:in `install'
	from ./bin/build_frameworks.rb:61:in `<main>'
`````
My fail message very simlar with @EMakadiya
But the root cause just I am not install `cmake` ...
thanks for your support

**Comment by EMakadiya** [comment]
Hello @twelve17,

I also have autoconf.

Can you please guide me how to run  automake command?

I tried but getting following error.

Making all in lib
/bin/sh: /Applications/Xcode: No such file or directory
make: *** [all-recursive] Error 1

**Comment by EMakadiya** [comment]
Hi @DaidoujiChen,

Is your problem solved?

**Comment by DaidoujiChen** [comment]
Hello @EMakadiya,

Yes, I solved.

**Comment by EMakadiya** [comment]
Hi @DaidoujiChen,

can you please help me.
how to run automake command?

**Comment by DaidoujiChen** [comment]
Hello @EMakadiya,

I am just missing `cmake`.

**Comment by EMakadiya** [comment]
@DaidoujiChen  

then how to solve this cmake issue?

**Comment by DaidoujiChen** [comment]
Hello @EMakadiya,

[requirements](https://github.com/twelve17/openalpr-ios#requirements) in project readme.

**Comment by EMakadiya** [comment]
@DaidoujiChen

I did all the things but still not facing issue.

**Comment by EMakadiya** [comment]
hi @DaidoujiChen,@twelve17,

Thanks for your support now i am able to run code. :+1: 
I just update the ruby version :dancer:

**Comment by twelve17** [comment]
Great, thanks.  I'll add some version and dependency checking to the script. :)

**Comment by twelve17** [comment]
@EMakadiya Out of curiosity, what version of ruby did you have that was giving you the broken behavior?

**Comment by DaidoujiChen** [comment]
:+1:

**Comment by ektapadaliya** [comment]
@twelve17 
old git version = 2.2.0
new git version = 2.6.4

I thought this "rvm reinstall 2.2.0 --disable-binary" command helped me.
