### ISSUE TITLE
Problems while installing

### ISSUE THREAD

**Issue by Skelzor** [twelve17/openalpr-ios#17]
I have some problems using bundle exec ./bin/build_frameworks.rb

I follow the instructions multiple times and come to the same problem(s):

```
imac-wlan:openalpr-ios-master skelzor$ bundle exec ./bin/build_frameworks.rb
options: {}
Downloading opencv2 library.
adding opencv2 headers symlink hack: /Users/skelzor/Developer/openalpr-ios-master/output/opencv2.framework/Headers/opencv2 -> /Users/skelzor/Developer/openalpr-ios-master/output/opencv2.framework/Headers
Downloading leptonica library.
Building leptonica for armv7 from /Users/skelzor/Developer/openalpr-ios-master/work/leptonica-1.71
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `distclean'.  Stop.
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: WARNING: using cross tools not prefixed with host triplet
Building leptonica for armv7s from /Users/skelzor/Developer/openalpr-ios-master/work/leptonica-1.71
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: WARNING: using cross tools not prefixed with host triplet
Building leptonica for arm64 from /Users/skelzor/Developer/openalpr-ios-master/work/leptonica-1.71
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: WARNING: using cross tools not prefixed with host triplet
Building leptonica for i386 from /Users/skelzor/Developer/openalpr-ios-master/work/leptonica-1.71
Building leptonica for x86_64 from /Users/skelzor/Developer/openalpr-ios-master/work/leptonica-1.71
Downloading tesseract library.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   372    0   372    0     0     40      0 --:--:--  0:00:09 --:--:--    93
100 12.2M    0 12.2M    0     0  1108k      0 --:--:--  0:00:11 --:--:-- 11.0M
Building tesseract for armv7 from /Users/skelzor/Developer/openalpr-ios-master/work/tesseract-3.03
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `distclean'.  Stop.
/Users/skelzor/Developer/openalpr-ios-master/lib/alpr/utils.rb:44:in `execute': Child returned: pid 28285 exit 1 (RuntimeError)
    from /Users/skelzor/Developer/openalpr-ios-master/lib/alpr/utils.rb:74:in `log_execute'
    from /Users/skelzor/Developer/openalpr-ios-master/lib/alpr/package/automake.rb:141:in `do_autoconf_build'
    from /Users/skelzor/Developer/openalpr-ios-master/lib/alpr/package/automake.rb:58:in `build_arch'
    from /Users/skelzor/Developer/openalpr-ios-master/lib/alpr/package/base.rb:53:in `block in install'
    from /Users/skelzor/Developer/openalpr-ios-master/lib/alpr/package/base.rb:52:in `each'
    from /Users/skelzor/Developer/openalpr-ios-master/lib/alpr/package/base.rb:52:in `install'
    from ./bin/build_frameworks.rb:76:in `<main>'
imac-wlan:openalpr-ios-master skelzor$ 
```

everything is unlinked / not installed like in the instructions. I use homebrew 0.9.5 and ruby 2.3. bundler has version 1.11.2.

I also recognize errors when working with Alcatraz-Plugins.

Thank you for any hint and the work on this framework - we already use it with Android.

**Comment by nicpro85** [comment]
is your problem that you get leptonica opencv and tesseract but not the openalpr framework in the output folder? Becaus that's what I get. The log file shows something like

> Running aclocal
> 
> Something went wrong, bailing out!

**Comment by Skelzor** [comment]
Yeah - but it looks like tesseract is also not complete included in the output folder. I think is a makefile-problem in Tesseract.

**Comment by nicpro85** [comment]
Yes, I solved the problem I think. I've been able complete the entire compilation script. I was missing libraries that I've installed using brew. there was "automake", "libtool", "autoconf", "autotools" and maybe one or two other ones. look at the log and google the last word before the message saying it had to stop.

**Comment by Skelzor** [comment]
Thank you very much - this works well for me! If I have a little bit time, I will make a Pull Request for the README.
