### ISSUE TITLE
Problem building tesseract-3.03 framework

### ISSUE THREAD

**Issue by ik2wxx** [twelve17/openalpr-ios#25]
Hello all

I have this error:

_---
Building tesseract for armv7 from /Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03
make: **\* No rule to make target `clean'.  Stop.
make: *** No rule to make target`distclean'.  Stop.
bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)
RuntimeError: Child returned: pid 43641 exit 1
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/utils.rb:44:in `execute'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/utils.rb:74:in`log_execute'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/package/automake.rb:141:in `do_autoconf_build'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/package/automake.rb:58:in`build_arch'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/package/base.rb:53:in `block in install'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/package/base.rb:52:in`each'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/package/base.rb:52:in `install'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/bin/build_frameworks.rb:76:in`<top (required)>'
---_

while doing "bundle exec ./bin/build_frameworks.rb"

framework is downloaded but looks like it can't find any suitable makefile.

Any help please ?

Tnx
Roberto

**Comment by twelve17** [comment]
Hi @ik2wxx , can you attach the build log?

**Comment by ik2wxx** [comment]
Hello
First of all, I have to say that every time I start the "bundle exec...." command, the result is different.
This is why the issue had another title and then I needed to change it.
So now the error is different, I copy here the messages:

---

options: {}
Package opencv2 is already installed. Skipping build.
Package leptonica is already installed. Skipping build.
Building tesseract for armv7 from /Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03
/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing: Unknown `--is-lightweight' option
Try`/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: WARNING: using cross tools not prefixed with host triplet
configure: WARNING: Training tools WILL NOT be built because of missing pango library.
configure: WARNING: Try to install libpango1.0-dev package.
configure: WARNING: Training tools WILL NOT be built because of missing cairo library.
configure: WARNING: Try to install libcairo-dev?? package.
Building tesseract for armv7s from /Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03
/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing: Unknown `--is-lightweight' option
Try`/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: WARNING: using cross tools not prefixed with host triplet
configure: WARNING: Training tools WILL NOT be built because of missing pango library.
configure: WARNING: Try to install libpango1.0-dev package.
configure: WARNING: Training tools WILL NOT be built because of missing cairo library.
configure: WARNING: Try to install libcairo-dev?? package.
Building tesseract for arm64 from /Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03
/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing: Unknown `--is-lightweight' option
Try`/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: WARNING: using cross tools not prefixed with host triplet
configure: WARNING: Training tools WILL NOT be built because of missing pango library.
configure: WARNING: Try to install libpango1.0-dev package.
configure: WARNING: Training tools WILL NOT be built because of missing cairo library.
configure: WARNING: Try to install libcairo-dev?? package.
Building tesseract for i386 from /Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03
/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing: Unknown `--is-lightweight' option
Try`/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: WARNING: Training tools WILL NOT be built because of missing pango library.
configure: WARNING: Try to install libpango1.0-dev package.
configure: WARNING: Training tools WILL NOT be built because of missing cairo library.
configure: WARNING: Try to install libcairo-dev?? package.
Building tesseract for x86_64 from /Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03
/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing: Unknown `--is-lightweight' option
Try`/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-3.03/config/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: WARNING: Training tools WILL NOT be built because of missing pango library.
configure: WARNING: Try to install libpango1.0-dev package.
configure: WARNING: Training tools WILL NOT be built because of missing cairo library.
configure: WARNING: Try to install libcairo-dev?? package.
bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)
RuntimeError: Got fatal error during LIPO: fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: archive member /Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-thin-lib/iPhoneOS-armv7/libtesseract_all.a(argz.o) cputype (16777223) and cpusubtype (3) does not match previous archive members cputype (12) and cpusubtype (9) (all members must match)

  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/package/base.rb:217:in `block in lipo_libraries'
  /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/find.rb:49:in`block (2 levels) in find'
  /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/find.rb:48:in `catch'
  /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/find.rb:48:in`block in find'
  /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/find.rb:43:in `each'
  /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/find.rb:43:in`find'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/package/base.rb:193:in `lipo_libraries'
  /Users/roberto/Desktop/Targhe/openalpr-ios-master/lib/alpr/package/base.rb:55:in`install'

##   /Users/roberto/Desktop/Targhe/openalpr-ios-master/bin/build_frameworks.rb:76:in `<top (required)>'

Thank you for help
Roberto

**Comment by twelve17** [comment]
Hmm, this part is strange:

```
/Users/roberto/Desktop/Targhe/openalpr-ios-master/work/tesseract-thin-lib/iPhoneOS-armv7/libtesseract_all.a(argz.o) cputype (16777223) and cpusubtype (3) does not match previous archive members cputype (12) and cpusubtype (9) (all members must match)
```

Can you delete the "work" directory and try again?
