### ISSUE TITLE
Not able to compile framework

### ISSUE THREAD

**Issue by TheMrugraj** [twelve17/openalpr-ios#26]
Hello

I tried to run `build_frameworks.rb` and received following errors

```
SyntaxError: /Users/pc5/Downloads/DEMO/openalpr-ios/lib/alpr/package/alpr.rb:31: syntax error, unexpected ','
    def initialize(log_file:, logger:,
                             ^
/Users/pc5/Downloads/DEMO/openalpr-ios/lib/alpr/package/alpr.rb:173: syntax error, unexpected keyword_end, expecting end-of-input
  /Users/pc5/Downloads/DEMO/openalpr-ios/lib/alpr/package.rb:1:in `require_relative'
  /Users/pc5/Downloads/DEMO/openalpr-ios/lib/alpr/package.rb:1:in `<top (required)>'
  /Users/pc5/Downloads/DEMO/openalpr-ios/bin/build_frameworks.rb:30:in `require_relative'
  /Users/pc5/Downloads//DEMO/openalpr-ios/bin/build_frameworks.rb:30:in `<top (required)>'
```

Please suggest solution 

Thanks in advance
Mrugraj

**Comment by twelve17** [comment]
Hi @mrugrajsinh , what version of ruby are you using?

**Comment by TheMrugraj** [comment]
```
$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin15.0]
```

**Comment by twelve17** [comment]
Can you confirm that is indeed the version the script is running?  That error is indicative of a pre 2.1 version of ruby.

**Comment by Andrei-Novikov** [comment]
Hello
I tried to run build_frameworks.rb and received following errors

Building openalpr for armv7 from /Users/Navigator/Documents/Projects/test/openalpr-ios/work/openalpr
bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)
RuntimeError: Child returned: pid 60748 exit 65
  /Users/Navigator/Documents/Projects/test/openalpr-ios/lib/alpr/utils.rb:44:in `execute'
  /Users/Navigator/Documents/Projects/test/openalpr-ios/lib/alpr/utils.rb:74:in`log_execute'
  /Users/Navigator/Documents/Projects/test/openalpr-ios/lib/alpr/package/alpr.rb:116:in `block in build_arch'
  /Users/Navigator/Documents/Projects/test/openalpr-ios/lib/alpr/package/alpr.rb:115:in`each'
  /Users/Navigator/Documents/Projects/test/openalpr-ios/lib/alpr/package/alpr.rb:115:in `build_arch'
  /Users/Navigator/Documents/Projects/test/openalpr-ios/lib/alpr/package/base.rb:53:in`block in install'
  /Users/Navigator/Documents/Projects/test/openalpr-ios/lib/alpr/package/base.rb:52:in `each'
  /Users/Navigator/Documents/Projects/test/openalpr-ios/lib/alpr/package/base.rb:52:in`install'
  /Users/Navigator/Documents/Projects/test/openalpr-ios/bin/build_frameworks.rb:84:in `<top (required)>'

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
MacOS Sierra, xcode 8.0

**Comment by wicheda** [comment]
@Navigator-Brest just wondering if you ever resolved your issue, I think I have the same problem as you.

**Comment by wicheda** [comment]
@Navigator-Brest After further investigation, I found the issue was outputted in build.log, it related to the code signing being invalid. Anarchid gave some great hints at: https://github.com/twelve17/openalpr-ios/issues/30#issuecomment-261887794
