### ISSUE TITLE
bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)

### ISSUE THREAD

**Issue by burf2000** [twelve17/openalpr-ios#31]
A error that seems common but I not seen how to fix it

I run bundle exec ./bin/build_frameworks.rb

options: {}
Package opencv2 is already installed. Skipping build.
Package leptonica is already installed. Skipping build.
Building tesseract for armv7 from /Users/burfies1/openalpr/openalpr-ios/work/tesseract-3.03
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `distclean'.  Stop.
bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)
RuntimeError: Child returned: pid 73905 exit 1
  /Users/burfies1/openalpr/openalpr-ios/lib/alpr/utils.rb:44:in `execute'
  /Users/burfies1/openalpr/openalpr-ios/lib/alpr/utils.rb:74:in `log_execute'
  /Users/burfies1/openalpr/openalpr-ios/lib/alpr/package/automake.rb:141:in `do_autoconf_build'
  /Users/burfies1/openalpr/openalpr-ios/lib/alpr/package/automake.rb:58:in `build_arch'
  /Users/burfies1/openalpr/openalpr-ios/lib/alpr/package/base.rb:53:in `block in install'
  /Users/burfies1/openalpr/openalpr-ios/lib/alpr/package/base.rb:52:in `each'
  /Users/burfies1/openalpr/openalpr-ios/lib/alpr/package/base.rb:52:in `install'
  /Users/burfies1/openalpr/openalpr-ios/bin/build_frameworks.rb:76:in `<top (required)>'

I am using latest xcode (8), have xcode command line tools install, cmake, autoconf etc

**Comment by TheWildHorse** [comment]
Same problem, did you find a fix @burf2000 ?

**Comment by XiangXu** [comment]
Same problem

**Comment by emericspiroux** [comment]
🆙

**Comment by twelve17** [comment]
@emericspiroux PRs are welcome

**Comment by GTMYang** [comment]
bundle exec ./bin/build_frameworks.rb
options: {}
Package opencv2 is already installed. Skipping build.
Building leptonica for armv7 from /Users/luoyang/openalpr-ios/work/leptonica-1.71
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: WARNING: using cross tools not prefixed with host triplet
bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)
RuntimeError: Child returned: pid 46968 exit 2
  /Users/luoyang/openalpr-ios/lib/alpr/utils.rb:44:in `execute'
  /Users/luoyang/openalpr-ios/lib/alpr/utils.rb:74:in `log_execute'
  /Users/luoyang/openalpr-ios/lib/alpr/package/automake.rb:147:in `do_autoconf_build'
  /Users/luoyang/openalpr-ios/lib/alpr/package/automake.rb:58:in `build_arch'
  /Users/luoyang/openalpr-ios/lib/alpr/package/base.rb:53:in `block in install'
  /Users/luoyang/openalpr-ios/lib/alpr/package/base.rb:52:in `each'
  /Users/luoyang/openalpr-ios/lib/alpr/package/base.rb:52:in `install'
  /Users/luoyang/openalpr-ios/bin/build_frameworks.rb:69:in `<top (required)>'

**Comment by federicocappelli** [comment]
Same here :/
(Mojave, xcode 10.1)
