### ISSUE TITLE
Build tesseract failed on ccutil

### ISSUE THREAD

**Issue by KoppeKTop** [twelve17/openalpr-ios#32]
Hello,

Following [build instructions](https://github.com/twelve17/openalpr-ios) trying to run `build_frameworks.rb` for commit 7e8040b81c007fe9af8558a5bd3d211f93ac9776, but it finishes with error.

```
bundle exec ./bin/build_frameworks.rb
options: {}
Downloading opencv2 library.
adding opencv2 headers symlink hack: /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/output/opencv2.framework/Headers/opencv2 -> /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/output/opencv2.framework/Headers
Downloading leptonica library.
Building leptonica for armv7 from /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/work/leptonica-1.71
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `distclean'.  Stop.
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: WARNING: using cross tools not prefixed with host triplet
Building leptonica for armv7s from /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/work/leptonica-1.71
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: WARNING: using cross tools not prefixed with host triplet
Building leptonica for arm64 from /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/work/leptonica-1.71
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: WARNING: using cross tools not prefixed with host triplet
Building leptonica for i386 from /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/work/leptonica-1.71
Building leptonica for x86_64 from /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/work/leptonica-1.71
Downloading tesseract library.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   372    0   372    0     0     36      0 --:--:--  0:00:10 --:--:--    93
100 12.2M    0 12.2M    0     0   760k      0 --:--:--  0:00:16 --:--:-- 2319k
Building tesseract for armv7 from /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/work/tesseract-3.03
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `distclean'.  Stop.
/Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/work/tesseract-3.03/config/missing: Unknown `--is-lightweight' option
Try `/Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/work/tesseract-3.03/config/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: WARNING: using cross tools not prefixed with host triplet
configure: WARNING: Training tools WILL NOT be built because of missing pango library.
configure: WARNING: Try to install libpango1.0-dev package.
configure: WARNING: Training tools WILL NOT be built because of missing cairo library.
configure: WARNING: Try to install libcairo-dev?? package.
bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)
RuntimeError: Child returned: pid 89479 exit 2
  /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/lib/alpr/utils.rb:44:in `execute'
  /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/lib/alpr/utils.rb:74:in `log_execute'
  /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/lib/alpr/package/automake.rb:147:in `do_autoconf_build'
  /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/lib/alpr/package/automake.rb:58:in `build_arch'
  /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/lib/alpr/package/base.rb:53:in `block in install'
  /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/lib/alpr/package/base.rb:52:in `each'
  /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/lib/alpr/package/base.rb:52:in `install'
  /Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/bin/build_frameworks.rb:76:in `<top (required)>'
```

Also [build.log.txt](https://github.com/twelve17/openalpr-ios/files/688336/build.log.txt) please find attached.

Version info:

- Mac OS X (El capitan, 10.11.6 (15G1212))
- ruby 2.1.2p95
- Bundler version 1.13.7
- Xcode and command line tools: 8.2.1 (8C1002)
- curl 7.43.0
- tar 2.8.3
- UnZip 5.52
- git 2.9.3
- cmake version 3.7.1 (homebrew)
- autoconf 2.69 (homebrew)

Maybe I've missed something? Appreciate any help.

**Comment by KoppeKTop** [comment]
I've tried to execute last instructions from build.log:

```
$ cd work/tesseract-3.03/ccutil
$ /bin/sh ../libtool  --tag=CXX   --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_CONFIG_H -I. -I..  -O2 -DNDEBUG   -arch armv7 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -miphoneos-version-min=9.0 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/usr/include/ -I/Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/output/leptonica.framework/Headers -I/Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/output/leptonica.framework/Headers/leptonica -DTESSDATA_PREFIX=/usr/local/share/  -arch armv7 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -miphoneos-version-min=9.0 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/usr/include/ -I/Users/andrey/Develop/black-sheep/taxi/license-ocr/openalpr-ios/output/leptonica.framework/Headers -std=c++11 -MT ambigs.lo -MD -MP -MF .deps/ambigs.Tpo -c -o ambigs.lo ambigs.cpp
```
And get libtool error:
```
libtool: Version mismatch error.  This is libtool 2.4.2 Debian-2.4.2-1ubuntu1, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2 Debian-2.4.2-1ubuntu1
libtool: and run autoconf again.
make[3]: *** [ambigs.lo] Error 63
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
Still no clue what goes wrong.
