### ISSUE TITLE
Got the problem to run bundle exec ./bin/build_frameworks.rb

### ISSUE THREAD

**Issue by zhouhao27** [twelve17/openalpr-ios#34]
Error message:

> bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)
> RuntimeError: Dependency 'cmake' is missing.  Please install it and try again.  See the README.md for details.
>   /Users/zhouhao/Downloads/openalpr-ios-master/bin/build_frameworks.rb:20:in `block in check_deps'
>   /Users/zhouhao/Downloads/openalpr-ios-master/bin/build_frameworks.rb:17:in `each'
>   /Users/zhouhao/Downloads/openalpr-ios-master/bin/build_frameworks.rb:17:in `check_deps'
>   /Users/zhouhao/Downloads/openalpr-ios-master/bin/build_frameworks.rb:25:in `<top (required)>'
> 

I download Cmake.dmg and install. But it's installed in Application folder and there is no command line installed. What should I do ? Thanks.

**Comment by zhouhao27** [comment]
Fixed by:

> brew install cmake
