### ISSUE TITLE
bundle exec ./bin/build_frameworks.rb not creating output directory

### ISSUE THREAD

**Issue by syedabdulsamad** [twelve17/openalpr-ios#36]
Hi,

I want to use ALPR for my iOS app. I am trying to follow the instruction in github page. When i run `bundle exec ./bin/build_frameworks.rb` the command fails with the following errors. 
```

bundler: failed to load command: ./bin/build_frameworks.rb (./bin/build_frameworks.rb)
RuntimeError: Child returned: pid 25248 exit 1
  /Users/abdulsamad/Documents/ALPR/lib/alpr/utils.rb:44:in `execute'
  /Users/abdulsamad/Documents/ALPR/lib/alpr/utils.rb:50:in `qexec'
  /Users/abdulsamad/Documents/ALPR/lib/alpr/package/automake.rb:37:in `<class:Automake>'
  /Users/abdulsamad/Documents/ALPR/lib/alpr/package/automake.rb:27:in `<module:Package>'
  /Users/abdulsamad/Documents/ALPR/lib/alpr/package/automake.rb:26:in `<top (required)>'
  /Users/abdulsamad/Documents/ALPR/lib/alpr/package.rb:2:in `require_relative'
  /Users/abdulsamad/Documents/ALPR/lib/alpr/package.rb:2:in `<top (required)>'
  /Users/abdulsamad/Documents/ALPR/bin/build_frameworks.rb:30:in `require_relative'
  /Users/abdulsamad/Documents/ALPR/bin/build_frameworks.rb:30:in `<top (required)>'

```
Does anybody have an idea what is wrong here. Can someone guide me to the right direction please.

Thanks 
Abdul

**Comment by Ross-Gibson** [comment]
@syedabdulsamad take a look here: https://github.com/twelve17/openalpr-ios/issues/30#issuecomment-261887794

**Comment by yurinativo** [comment]
I got this error too.
Tracing the log, the problem occurred on automaker.rb:37 when it tries to execute the line below:
`xcrun --sdk iphoneos --show-sdk-path`.

Running this line on terminal, I got an error:
`SDK “iphoneos” cannot be located`

This is because the command line tools was not set correctly.

To solve this:

1. Open the **Xcode**
2. Open the **Preferences**
3. Go to the **Locations** tab
4. Select the Xcode Version on **Command Line Tools** field. (Mine was blank)
